[package]
name = "rs_tip_syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rowan = "0.15.11"
rs_tip_lexer = { path = "../rs_tip_lexer" }
